# Generated by Django 3.2.13 on 2023-01-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hello! this is the profile for <django.db.models.fields.related.OneToOneField>.', max_length=300),
        ),
    ]
