# Generated by Django 3.2.13 on 2023-01-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hello! this is the profile for <django.db.models.query_utils.DeferredAttribute object at 0x7fb0a7cabaf0>.', max_length=300),
        ),
    ]
