# Generated by Django 3.2.13 on 2023-01-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='Hello! Welcome to my profile. Feel free to send me a request!', max_length=300),
        ),
    ]
