# Generated by Django 3.2.13 on 2022-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220627_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='task_items/'),
        ),
    ]
