# Generated by Django 3.2.13 on 2022-06-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskitem_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='attached_file',
        ),
    ]
