# Generated by Django 3.2.13 on 2022-06-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20220627_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='attached_file',
        ),
    ]
