# Generated by Django 3.2.13 on 2022-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_taskitem_attached_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_request',
            field=models.BooleanField(default=False),
        ),
    ]
