# Generated by Django 3.2.13 on 2022-12-31 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_task_is_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='request_accepted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='requestee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to=settings.AUTH_USER_MODEL),
        ),
    ]
