# Generated by Django 3.2.13 on 2023-01-04 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_auto_20221231_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='requestee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
