# Generated by Django 3.2.13 on 2023-01-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_requestee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='requestee',
            new_name='requested_by',
        ),
    ]
