# Generated by Django 3.2.13 on 2023-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20230104_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_request',
        ),
        migrations.AlterField(
            model_name='task',
            name='request_accepted',
            field=models.BooleanField(null=True),
        ),
    ]
