# Generated by Django 3.2.13 on 2023-01-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20230108_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='request_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
