# Generated by Django 3.2.13 on 2023-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_task_request_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='request_accepted',
            field=models.IntegerField(default=0),
        ),
    ]
