# Generated by Django 3.2.13 on 2023-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_request_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='request_accepted',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
    ]
